# Generated by Django 3.0.3 on 2020-04-12 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(default='', max_length=90)),
                ('address', models.CharField(default='', max_length=90)),
                ('pmobile', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default='')),
                ('dob', models.CharField(default='', max_length=90)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Casepaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(default=1)),
                ('ctype', models.CharField(default='', max_length=90)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
