# Generated by Django 3.0.3 on 2020-04-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dactive',
            field=models.BooleanField(default=False),
        ),
    ]
